In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [320]:
vec = np.arange(1, 21)
f = lambda n: 2**n/n
f(vec)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [322]:
vec = np.arange(0, 5)
f = lambda i:0.1**(3*i)*0.2**(4*i)
f(vec).sum()


1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [312]:
np.fromfunction(lambda i, j: (i+j+1)%2, (8, 8))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [333]:
import math
X = np.random.random((5, 2))

def cart_to_polar(vec):
    x, y = vec
    return (x**2+y**2)**(1/2), math.atan(y/x)

np.apply_along_axis(cart_to_polar, 1, X)

array([[0.45811787, 0.63271223],
       [0.11355129, 0.7296857 ],
       [0.80074491, 1.01162381],
       [0.95372759, 0.44759609],
       [0.46447009, 0.86039883]])

**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [344]:
X = np.random.random((10, 10))
coords = (np.argmax(X)//10, np.argmax(X)%10)
X[coords]

0.992365052134141

In [345]:
# Но можно решить и при помощи np.where
coords = (np.where(X == X.max()))
X[coords]


array([0.99236505])

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [355]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

distances = np.linalg.norm(X - y, ord=2, axis=1)
print(f'Точка: {X[np.argmin(distances)]}\nИндекс: {np.argmin(distances)}\nРасстояние: {distances.min()}')


Точка: [0.54659241 0.31182551]
Индекс: 2
Расстояние: 0.13757729854851125


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [357]:
def f(x):
    if x < 0:
        return x**2 + 2*x + 6
    elif 0 <= x <= 2:
        return x+6
    else:
        return x**2+4*x-4
    
np.vectorize(f)(np.arange(-3, 4))


array([ 9,  6,  5,  6,  7,  8, 17])

In [359]:
# Если речь шла не о целых числах, можно использовать np.linspace
n=15
np.vectorize(f)(np.linspace(-3, 3, n))

array([ 9.        ,  7.46938776,  6.30612245,  5.51020408,  5.08163265,
        5.02040816,  5.32653061,  6.        ,  6.42857143,  6.85714286,
        7.28571429,  7.71428571,  9.16326531, 12.89795918, 17.        ])

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [69]:
X = np.random.random((10, 10))
np.mean(X - np.mean(X)), (X - np.mean(X))


(-4.218847493575595e-17,
 array([[ 0.26121445, -0.13101711,  0.46157848,  0.26174545, -0.31908295,
          0.40479588, -0.24043274, -0.23901225,  0.12877424,  0.02224926],
        [-0.38661018,  0.03570374, -0.27949296,  0.2026298 ,  0.44543561,
         -0.3873188 , -0.44679016,  0.11563698, -0.18828119,  0.24454626],
        [-0.47655045, -0.05979446,  0.24914713,  0.27596618, -0.40734399,
         -0.32972193,  0.28167769, -0.24430242, -0.06101845, -0.08397095],
        [ 0.22832575, -0.28594957,  0.31044296,  0.40801347, -0.37142746,
          0.42544781,  0.41693176, -0.21232812, -0.29974969, -0.03475247],
        [-0.32207446, -0.13751271,  0.03015982,  0.06923345,  0.05137943,
          0.15424502,  0.35044746,  0.39752759,  0.08954292, -0.35661505],
        [-0.30225514,  0.09180987,  0.12483296,  0.08599097,  0.48393574,
          0.31233965, -0.1721834 , -0.16815429, -0.09591501,  0.13677157],
        [ 0.39468955,  0.06094519,  0.44104342,  0.18993058, -0.34119733,
       

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [122]:
X = np.random.normal(loc=5, scale=2., size=1000)
np.mean(X), np.var(X)

(5.018022739605325, 4.00735532326278)

**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [116]:
np.fromfunction(lambda i, j: (i+j)%5, (5, 5))

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [306]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 4)    

[0, 0, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [307]:
def sample(x, c):
    vec = np.array(x)
    rand_vec = np.random.rand(c)*np.sum(vec)
    cumsum = np.transpose([np.cumsum(vec)])
    return np.argmax((rand_vec < cumsum).T, axis=1)

In [308]:
sample([50, 3, 1, 7, 20], 4)  

array([0, 4, 0, 0], dtype=int64)